import{Component,createElement}from"react";
import{ScrollView}from"react-native";
import{mergeNativeStyles}from"@mendix/pluggable-widgets-tools";
const defaultStyle={
	container:{},
	label:{
		color:"#F6BB42"
	}
};
export class ScrollViewComponent extends Component{
	styles=mergeNativeStyles(defaultStyle,this.props.style);
	constructor(props){
		super(props);
		this.scrollViewRef=null;
		this.busyScrolling=false;
	}
	componentDidMount(){
		if(!this.busyScrolling){
			this.busyScrolling=true;
			try{
				this.scrollViewRef.scrollToEnd({animated:true});
				this.busyScrolling=false;
			}catch(e){
				this.busyScrolling=false;
				console.warn(e.toString());
			}
		}
	}
	render(){
		return (
			<ScrollView
				ref={
					(scroll)=>{
						//console.warn("ScrollView:ref");
						this.scrollViewRef=scroll;
					}
				}
				style={this.styles.container}
				onContentSizeChange={()=>{
					setTimeout(()=>{
						if(!this.busyScrolling){
							this.busyScrolling=true;
							try{
								this.scrollViewRef.scrollToEnd({animated:true});
								this.busyScrolling=false;
							}catch(e){
								console.warn(e.toString());
								this.busyScrolling=false;
							}
						}
					},this.props.scrollTimeout);

				}}
			>
				{this.props.basicContent}
			</ScrollView>
		);
	}
}
